# Load the Rails application.
require_relative "application"

# Initialize the Rails application.
Rails.application.initialize!

Jbuilder.key_format camelize: :lower
Jbuilder.deep_format_keys true

# XUwPX0D76IDEZjGV9l7XIUk1zvK+jXB/cWVUdgObX6+cpqTwNvyKT8Hq4HSRLszYDKfEzKByNsTavop/FOEHBl/gGCWxF8itLm5vOsDd6woU4QiEsRfSQP1K7UyW1EYFmeKTWuL1VsNREYTeolN5OaEaVkV9CKAisS3KC/HVV2C49wmseInhKLZ/3qsgcYejwMyO3UrXkkajJVCR86tHpydPz1xL2VocFgEBFR5uS17tieaUttoAka/76wAp3TGIb67V0JIpAIHlwhxDRyPEAnvGEPNbs8bCQlB/ONsvCHvqG7eWw6CN227T+ZaRXqDi7ZkiubKZDwPbBV+jIoL+IIXyDSivF+fAxh7epyJmrowx7bWA1jhVpoyv1RjedYsNZeGQfX2Su6iIFbagyc28bK9AeXtc--95outNY/PuEQZs53--VTYBmD3GJxMQvMhiR5oJOg==